const descriptions = {
  EN: {
    headerTitle: "To-do list",
    themeLight: "Light Theme",
    themeDark: "Dark Theme",
    sectionTitle: "Add new task",
    tasksSectionTitle: "List of tasks",
    inputPlaceholder: "What are you going to do?",
    formButtonInnerText: "Add task",
    setDoneButtonInnerText: "Finish all",
    removeAllInnerText: "Remove all",
    toggleButtonInnerTextHidden: "Show done",
    toggleButtonInnerTextVisible: "Hide done",
    getExampleTaskButton: "Get example tasks",
    tasksPageTitle: "Tasks",
    taskPageTitle: "Task details",
    taskStatusLabel: "Completed:",
    taskStatusDone: " Yes",
    taskStatusUndone: " No",
    taskStatusNotFound: "Unfortunately, the task not found😢",
    searchSectionTitle: "Search",
    searchLabelPlaceholder: "Filter tasks",
    getExampleTasksLoader: "Loading...",
    authorPageTitle: "About author",
    authorPageContent: "Hi, my name is Natalia and I am an animal lover. I have a dog and three parrots🐶🦜🐦🐦. I graduated from college - Spanish language in business and tourism. In my first job I gently encountered programming - which I really liked, but somehow at that time I didn't think about it seriously. Recently, this has changed and I have decided that I am starting to learn programming! In addition to programming, I'm also interested in interior design, I like painting, but lately (mostly due to pandemic times) I've become...a plant freak🌱🌵🌷🌺.",
    errorPage: "Error 404 - page not found",
    errorPageContent: "The page with the address does not exist😒",
    pageLink: "Back to Home Page",
    extraContentNoTasks: "📌You currently have no tasks on the list",
    extraContentHideDone: "📌You have hidden completed tasks - click 'Show done'",
    extraContentEmptyList: "🧷No more tasks for you",
    edit: "Edit",
    remove: "Remove",
    save: "Save",
  },
  PL: {
    headerTitle: "Lista zadań",
    themeLight: "Jasny motyw",
    themeDark: "Ciemny motyw",
    sectionTitle: "Dodaj nowe zadanie",
    tasksSectionTitle: "Lista zadań",
    inputPlaceholder: "Co jest do zrobienia?",
    formButtonInnerText: "Dodaj zadanie",
    setDoneButtonInnerText: "Ukończ wszystkie",
    removeAllInnerText: "Usuń wszystkie",
    toggleButtonInnerTextHidden: "Pokaż ukończone",
    toggleButtonInnerTextVisible: "Ukryj ukończone",
    getExampleTaskButton: "Pobierz przykładowe zadania",
    tasksPageTitle: "Zadania",
    taskPageTitle: "Szczegóły zadania",
    taskStatusLabel: "Ukończono:",
    taskStatusDone: " Tak",
    taskStatusUndone: " Nie",
    taskStatusNotFound: "Niestety, nie znaleziono zadania😢",
    searchSectionTitle: "Wyszukiwarka",
    searchLabelPlaceholder: "Filtruj zadania",
    getExampleTasksLoader: "Ładowanie...",
    authorPageTitle: "O autorze",
    authorPageContent: "Cześć! Nazywam się Natalia i jestem miłośniczką zwierząt. Sama posiadam psa i trzy papugi🐶🦜🐦🐦. Ukończyłam studia - iberystykę, a dokładniej język hiszpański w biznesie i turystyce. W swojej pierwszej pracy delikatnie zetknęłam się z programowaniem - co mi się bardzo spodobało, jednak jakoś wtedy nie myślałam o tym na poważnie. Ostatnio się to zmieniło i postanowiłam, że rozpoczynam naukę programowania! Poza programowaniem interesuję się również aranżacją wnętrz, lubię też czasami namalować obraz, ale ostatnimi czasy (głównie przez czasy pandemiczne) stałam się...maniaczką roślinną🌱🌵🌷🌺.",
    errorPage: "Błąd 404 - nie znaleziono strony",
    errorPageContent: "Strona o podanym adresie nie istnieje😒",
    pageLink: "Powrót do Strony Głównej",
    extraContentNoTasks: "📌Nie masz aktualnie żadnych zadań na liście",
    extraContentHideDone: "📌Masz ukryte ukończone zadania - kliknij 'Pokaż ukończone'",
    extraContentEmptyList: "🧷Nie masz więcej zadań",
    edit: "Edytuj",
    remove: "Usuń",
    save: "Zapisz",
  },
  ES: {
    headerTitle: "Lista zadań",
    themeLight: "Jasny motyw",
    themeDark: "Ciemny motyw",
    sectionTitle: "Dodaj nowe zadanie",
    tasksSectionTitle: "Lista zadań",
    inputPlaceholder: "Co jest do zrobienia?",
    formButtonInnerText: "Dodaj zadanie",
    setDoneButtonInnerText: "Ukończ wszystkie",
    removeAllInnerText: "Usuń wszystkie",
    toggleButtonInnerTextHidden: "Pokaż ukończone",
    toggleButtonInnerTextVisible: "Ukryj ukończone",
    getExampleTaskButton: "Pobierz przykładowe zadania",
    tasksPageTitle: "Zadania",
    taskPageTitle: "Szczegóły zadania",
    taskStatusLabel: "Ukończono:",
    taskStatusDone: " Tak",
    taskStatusUndone: " Nie",
    taskStatusNotFound: "Niestety, nie znaleziono zadania😢",
    searchSectionTitle: "Wyszukiwarka",
    searchLabelPlaceholder: "Filtruj zadania",
    getExampleTasksLoader: "Ładowanie...",
    authorPageTitle: "O autorze",
    authorPageContent: "Cześć! Nazywam się Natalia i jestem miłośniczką zwierząt. Sama posiadam psa i trzy papugi🐶🦜🐦🐦. Ukończyłam studia - iberystykę, a dokładniej język hiszpański w biznesie i turystyce. W swojej pierwszej pracy delikatnie zetknęłam się z programowaniem - co mi się bardzo spodobało, jednak jakoś wtedy nie myślałam o tym na poważnie. Ostatnio się to zmieniło i postanowiłam, że rozpoczynam naukę programowania! Poza programowaniem interesuję się również aranżacją wnętrz, lubię też czasami namalować obraz, ale ostatnimi czasy (głównie przez czasy pandemiczne) stałam się...maniaczką roślinną🌱🌵🌷🌺.",
    errorPage: "Błąd 404 - nie znaleziono strony",
    errorPageContent: "Strona o podanym adresie nie istnieje😒",
    pageLink: "Powrót do Strony Głównej",
    extraContentNoTasks: "📌Nie masz aktualnie żadnych zadań na liście",
    extraContentHideDone: "📌Masz ukryte ukończone zadania - kliknij 'Pokaż ukończone'",
    extraContentEmptyList: "🧷Nie masz więcej zadań",
    edit: "Edytuj",
    remove: "Usuń",
    save: "Zapisz",
  }
};

export default descriptions;